name: Scrape Cotepara V2

on:
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install packages
        run: |
          pip install requests beautifulsoup4 pandas lxml

      - name: Run scraper V2
        run: |
          python scrape_cotepara_v2.py

      - name: Show files
        run: |
          ls -lh

      - name: Upload CSV
        uses: actions/upload-artifact@v4
        with:
          name: products-cotepara-v2
          path: products_cotepara_v2.csv
